### ISSUE TITLE
ROS 2 port

### ISSUE THREAD

**Issue by vmayoral** [ros/eigen_stl_containers#15]
@clalancette I went ahead and ported the package to ROS 2.0 https://github.com/AcutronicRobotics/eigen_stl_containers/tree/ros2.

Probably worth creating a repo under github.com/ros2.

Cheers,

**Comment by clalancette** [comment]
@vmayoral We've been changing our practices to have a different branch on the same repository, rather than forking everything into the ros2 organization.  Towards that end, I've created the `ros2` branch on this repository; feel free to open a PR against that branch.  And thanks!

**Comment by vmayoral** [comment]
Understood. Thanks @clalancette!

Closing here.

**Comment by vmayoral** [comment]
Follows at https://github.com/ros/eigen_stl_containers/pull/16
