### ISSUE TITLE
eigen_stl_containers fails on saucy

### ISSUE THREAD

**Issue by k-okada** [ros/eigen_stl_containers#7]
https://github.com/ros-gbp/eigen_stl_containers-release/issues/1#issuecomment-257731858

the problem was https://github.com/ros/eigen_stl_containers/commit/ceb6c4d5a58e8de5c67ec17e5e51717e507839ef but if we revert this, we'll have 
https://github.com/ros/robot_model/issues/149 issue for kinetic, one option is to release 1.0.5 for indigo/jade and 1.0.6 for kinetic, otherwise, we'll have to write something like
```
find_pakcge(Eigen3)
if(NOT Eigen3_FOUND)
  find_package(Eigen Eigen3)
endif()
```

**Comment by clalancette** [comment]
So, I took a quick look at this.  I don't think your proposed solution of using the if statement is going to work on all of our supported platforms.  In particular, libeigen3-dev in Ubuntu saucy (still supported by Indigo) doesn't have a cmake file *at all* so find_package will never work there.  All of the Ubuntu releases past Saucy (and Debian Jessie) do seem to have a cmake component for eigen.

Thus, my suggestion is that we branch this package into two streams, indigo and kinetic.  The indigo branch would revert the patch from https://github.com/ros/eigen_stl_containers/commit/ceb6c4d5a58e8de5c67ec17e5e51717e507839ef , and the kinetic branch would keep it.  Does that make sense to you?  If so, I'll go ahead and do this.

**Comment by k-okada** [comment]
@clalancette If I was a maintainer of this package, I'll prefer to go with single branch for indigo/kinetic, because for me keep my eye on one single branch seems easier than keep two different branch update ( may be I am single-core processor machine...), but it's up to maintainers.

FYI, I have create PR ( https://github.com/ros/eigen_stl_containers/pull/11) that should works on both 13.10 and 14.04, which is basically as same as ->  https://github.com/ros-perception/image_pipeline/commit/88c609672222920cb434b37fa590b7e9475c5fb0

**Comment by wjwwood** [comment]
This might be relevant: http://wiki.ros.org/jade/Migration#Eigen_CMake_Module_in_cmake_modules

**Comment by clalancette** [comment]
I ended up merging k-okada's PR, and then slightly modifying it with the instructions from that ros.org wiki page.  I think this is resolved now, so I'll close this out.  Thanks!
